In [8]:
import pandas as pd 
import statsmodels.api as sm 
from pathlib import Path
import sys
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT))
import src.regression as kit

In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [10]:
PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

In [11]:
df = pd.read_csv(PROCESSED_DIR/"etf_ff5_merged.csv")
df["date"] = pd.to_datetime(df["date"])
df = df.drop(columns=["Unnamed: 0"], errors="ignore")
df.head()

,date,ticker,return,mkt_rf,smb,hml,rmw,cma,rf,excess_return
0,2015-02-28,IWM,0.059464,0.0614,0.0036,-0.0179,-0.0110,-0.0175,0.0,0.059464
1,2015-03-31,IWM,0.017700,-0.0109,0.0308,-0.0038,0.0007,-0.0062,0.0,0.017700
2,2015-04-30,IWM,-0.025649,0.0060,-0.0301,0.0180,0.0005,-0.0062,0.0,-0.025649
3,2015-05-31,IWM,0.022364,0.0138,0.0082,-0.0111,-0.0176,-0.0083,0.0,0.022364
4,2015-06-30,IWM,0.007829,-0.0154,0.0290,-0.0082,0.0035,-0.0154,0.0,0.007829

In [12]:
ticker = "IWM"

data = df[df["ticker"] == ticker].copy()
data = data.sort_values("date")

y = data["excess_return"]
X = data[["mkt_rf", "smb", "hml", "rmw", "cma"]]

X = sm.add_constant(X)

model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:          excess_return   R-squared:                       0.990
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     2524.
Date:                Mon, 04 May 2026   Prob (F-statistic):          3.09e-125
Time:                        14:31:21   Log-Likelihood:                 496.41
No. Observations:                 133   AIC:                            -980.8
Df Residuals:                     127   BIC:                            -963.5
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.0010      0.001     -1.805      0.073      -0.002    9.26e-05
mkt_rf         1.0006      0.013     78.716      0.000       0.975       1.026
smb            0.8161      0.022     37.292      0.000       0.773       0.859
hml            0.1058      0.020      5.313      0.000       0.066       0.145
rmw           -0.1154      0.027     -4.235      0.000      -0.169      -0.061
cma           -0.0349      0.029     -1.191      0.236      -0.093       0.023
==============================================================================
Omnibus:                        3.132   Durbin-Watson:                   2.051
Prob(Omnibus):                  0.209   Jarque-Bera (JB):                3.210
Skew:                           0.101   Prob(JB):                        0.201
Kurtosis:                       3.734   Cond. No.                         64.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [13]:
regression_summary, df_predictions = kit.run_factor_regression(df)

In [14]:
regression_summary.sort_values("ticker")

,ticker,alpha,beta_market,beta_smb,beta_hml,beta_rmw,beta_cma,r_squared,adj_r_squared,n_obs
0,IWM,-0.000964,1.000568,0.816066,0.105815,-0.115385,-0.034876,0.990035,0.989643,133
1,MTUM,0.000737,0.976609,-0.220917,-0.168358,-0.179279,0.174783,0.824980,0.818089,133
2,QQQ,0.002426,1.099168,-0.182041,-0.298270,-0.009181,-0.141128,0.933993,0.931394,133
3,QUAL,-0.000817,0.975596,-0.078069,-0.028178,0.209962,0.001249,0.968292,0.967043,133
4,SPY,-0.000187,0.981940,-0.106301,0.016696,0.069996,0.023812,0.996467,0.996328,133
5,USMV,-0.000828,0.710765,-0.121501,-0.022292,0.269796,0.174232,0.794793,0.786713,133
6,VLUE,-0.001258,0.985871,0.143373,0.383407,0.033927,0.083584,0.916592,0.913308,133
7,VTV,-0.000431,0.873500,-0.018879,0.297482,0.100198,0.183840,0.942589,0.940329,133
8,VUG,0.000337,1.092104,-0.169359,-0.251483,-0.007101,-0.158633,0.970257,0.969086,133